---
- name: 'Plan upgrade'
  command: >-
    kubeadm upgrade plan {{ kubeadm_version.version.split( '-' )|first }}
    {% for error in kubeadm_ignore_preflight_errors %}
    --ignore-preflight-errors={{ error }}
    {% endfor %}
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  register: plan_upgrade

- name: 'Display result of "kubectl upgrade plan"'
  debug:
    msg: >-
      {{ dict(stderr=plan_upgrade.stderr_lines,
              stdout=plan_upgrade.stdout_lines) }}

- name: 'Apply upgrade'
  command: >-
    kubeadm upgrade apply {{ kubeadm_version.version.split( '-' )|first }} -y
    {% for error in kubeadm_ignore_preflight_errors %}
    --ignore-preflight-errors={{ error }}
    {% endfor %}
    {% if kubeadm_upgrade_apply_force|bool %}
    --force
    {% endif %}
  register: apply_upgrade

- name: 'Display result of "kubectl upgrade apply"'
  debug:
    msg: >-
      {{ dict(stderr=apply_upgrade.stderr_lines,
              stdout=apply_upgrade.stdout_lines) }}
