---
- name: "Upgrade to haproxy"
  block:
  - name: "Stop compose stack"
    community.docker.docker_compose_v2:
      project_src: '{{ apiserver_proxy_stack_dir }}'
      state: absent
    vars:
      ansible_python_interpreter: >-
        {%- if ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04" -%}
          /usr/bin/python2
        {%- else -%}
          {{ ansible_python.executable }}
        {%- endif -%}
    when: has_docker_compose|bool

  - name: "Reload haproxy"
    service:
      name: haproxy
      state: reloaded
    when: not(_haproxy_repo_just_added is changed and ansible_check_mode)

  rescue:
  - name: "Restart compose stack if error occured"
    community.docker.docker_compose_v2:
      project_src: '{{ apiserver_proxy_stack_dir }}'
      state: present
    vars:
      ansible_python_interpreter: >-
        {%- if ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04" -%}
          /usr/bin/python2
        {%- else -%}
          {{ ansible_python.executable }}
        {%- endif -%}
    when: has_docker_compose|bool

- name: "Remove compose stack to finish upgrade"
  file:
    dest: "{{ apiserver_proxy_stack_dir }}"
    state: absent
