---
- name: "Extract public key from kubernetes CA"
  command: openssl x509 -noout -pubkey -in {{ _kubernetes_ca_cert }}
  check_mode: false
  changed_when: false
  delegate_to: '{{ cp_node }}'
  run_once: true
  register: _kubernetes_ca_fingerprint

- name: "Compute sha256 of fingertprint"
  set_fact:
    ca_cert_hash: >-
      {{ _kubernetes_ca_fingerprint.stdout|regex_replace('[- A-Z]+\n([+/\w\n]+)\n[- A-Z]+', '\g<1>')|b64decode|hash('sha256') }}
  run_once: true
