---
_kubelet_config_path: /var/lib/kubelet/config.yaml
enable_kubeadm_patches: true
kubeadm_ignore_preflight_errors: []
kubeadm_patch_dir: /etc/kubernetes/patches
kube_cp_group: kube_control_plane
kube_worker_group: kube_workers

cp_node: '{{ (groups.cp_running|default(groups[kube_cp_group]))|first }}'

_target_kube_version: '{{ hostvars[cp_node]._target_kube_version }}'
_target_kubeadm_version: '{{ hostvars[cp_node]._target_kubeadm_version }}'
