---
- name: 'Drain node if needed'
  command: >-
    kubectl drain
    --ignore-daemonsets
    {% if delete_emptydir_data|bool %}
    --delete-emptydir-data
    {% endif %}
    {% if delete_local_data|bool %}
    --delete-local-data
    {% endif %}
    {{ ansible_nodename }}
  delegate_to: '{{ cp_node }}'
  when: drain_node|bool
  notify:
  - Reboot node
  - Wait for node
  - Uncordon node
