---
- name: 'Pause before drain'
  pause:
  when: pause_before_drain|bool

- name: 'Drain node if needed'
  command: >-
    kubectl drain
    --ignore-daemonsets
    {% if delete_emptydir_data|bool %}
    --delete-emptydir-data
    {% endif %}
    {% if delete_local_data|bool %}
    --delete-local-data
    {% endif %}
    {% if drain_force|bool %}
    --force
    {% endif %}
    {{ ansible_nodename }}
  delegate_to: '{{ cp_node }}'
  when: drain_node|bool
  notify:
  - Pause after upgrade
  - Restart kubelet
  - Reboot node
  - Wait for node
  - Uncordon node

- include_role:
    name: hooks_call
  vars:
    kubeadm_hook_list: ['pre_nodes_upgrade']
